# Generated by Django 5.1.4 on 2025-01-30 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_payment_checkout_id_uniqueurl_in_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phn_no',
            new_name='phone_no',
        ),
    ]
