# Generated by Django 5.1.4 on 2025-02-02 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ecommerceapp.details'),
        ),
    ]
